services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_DATABASE_HOST: db
      - FLASK_DATABASE: mailer-db
      - FLASK_DATABASE_USER: root
      - FLASK_DATABASE_PASSWORD: admin
      - FROM_EMAIL: yourMail@example.com
      - SECRET_KEY: yourSecretKey
      - SENDGRID_API_KEY: yourSendGridAPIKey

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: mailer-db
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local